name: Build EXE

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ./installResources.ps1

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile project.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-exe
        path: dist/project.exe
